name: CI

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "vcpkg.json"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "vcpkg.json"
      - ".github/workflows/ci.yml"

jobs:
  build-and-test:
    runs-on: windows-2025-vs2026

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: e6ebaa9c3ca8fca90c63af62fc895c2486609580

      - name: Configure CMake
        run: cmake --preset default

      - name: Build
        run: cmake --build --preset debug

      - name: Disable crash dialogs
        run: |
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v DontShowUI /t REG_DWORD /d 1 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting" /v Disabled /t REG_DWORD /d 1 /f

      - name: Test
        run: ctest --preset debug
